# Generated by Django 4.0.3 on 2022-03-14 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 18, 12, 11688))),
            ],
        ),
    ]
