# Generated by Django 4.0.3 on 2022-03-14 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 28, 58, 901672)),
        ),
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
    ]
