# Generated by Django 4.0.3 on 2022-03-25 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_alter_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 18, 49, 41, 759605)),
        ),
    ]
