# Generated by Django 4.0.3 on 2022-05-26 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_alter_file_created_at_alter_file_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 18, 15, 18, 592586)),
        ),
    ]
