# Generated by Django 4.0.3 on 2022-03-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
