# Generated by Django 4.0.3 on 2022-03-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_alter_file_created_at'),
        ('account', '0003_remove_account_file_id_account_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
