# Generated by Django 4.0.3 on 2022-03-14 03:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0004_alter_file_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=30)),
                ('prepared_time', models.IntegerField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 20, 12, 684576))),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
