# Generated by Django 4.0.3 on 2022-03-16 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_alter_file_created_at'),
        ('recipe', '0004_alter_recipe_created_at_alter_recipe_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 18, 12, 4, 855952)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='file_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
