# Generated by Django 4.0.3 on 2022-03-16 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_created_at_alter_recipe_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 18, 15, 17, 989061)),
        ),
    ]
