# Generated by Django 4.0.3 on 2022-03-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='file',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 18, 20, 49, 465166)),
        ),
    ]
