# Generated by Django 4.0.3 on 2022-03-25 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_rename_file_recipe_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 18, 40, 4, 786618)),
        ),
    ]
