# Generated by Django 4.0.3 on 2022-03-28 01:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_alter_bookmark_created_at_alter_bookmark_table'),
        ('procedure', '0007_alter_procedure_created_at_alter_procedure_table'),
        ('comments', '0003_alter_comment_table'),
        ('file', '0012_alter_file_created_at_alter_file_table'),
        ('recipe', '0011_alter_recipe_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBookmarks',
            fields=[
                ('bookmark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookmarks.bookmark')),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'bookmarks',
            },
            bases=('bookmarks.bookmark',),
        ),
        migrations.CreateModel(
            name='AdminComments',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.comment')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
            },
            bases=('comments.comment',),
        ),
        migrations.CreateModel(
            name='AdminFiles',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file.file')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'db_table': 'files',
            },
            bases=('file.file',),
        ),
        migrations.CreateModel(
            name='AdminProcedures',
            fields=[
                ('procedure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='procedure.procedure')),
            ],
            options={
                'verbose_name_plural': 'Procedures',
                'db_table': 'procedures',
            },
            bases=('procedure.procedure',),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 9, 22, 51, 750093)),
        ),
    ]
