# Generated by Django 4.0.3 on 2022-05-26 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_adminbookmarks_admincomments_adminfiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 18, 15, 18, 616585)),
        ),
    ]
