# Generated by Django 4.0.3 on 2022-03-14 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0003_alter_file_created_at'),
        ('recipe', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.TextField()),
                ('order', models.IntegerField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 19, 54, 947411))),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
