# Generated by Django 4.0.3 on 2022-03-14 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 28, 58, 904707)),
        ),
        migrations.AlterModelTable(
            name='procedure',
            table='procedures',
        ),
    ]
