# Generated by Django 4.0.3 on 2022-03-25 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0005_alter_procedure_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 18, 40, 4, 786618)),
        ),
    ]
